/* W12 · flatten v_portal_feed into the Google Sheet the existing portal reads.
 * Arrays become pipe-delimited so the sheet stays human-scannable and the
 * portal's existing string parsing keeps working. */
const join = a => (Array.isArray(a) ? a : []).filter(Boolean).join(' | ');
return $input.all().map(({ json: o }) => ({ json: {
  id: o.id,
  title: o.title,
  organisation: o.organisation || '',
  type: o.type,
  degree_levels: join(o.degree_levels),
  fields_of_study: join(o.fields_of_study),
  host_country: o.host_country || '',
  host_region: o.host_region || '',
  is_remote: o.is_remote ? 'yes' : 'no',
  funding: o.funding,
  funding_detail: o.funding_detail || '',
  deadline: o.deadline || '',
  deadline_kind: o.deadline_kind,
  deadline_note: o.deadline_note || '',
  days_left: o.days_left === null || o.days_left === undefined ? '' : o.days_left,
  duration: o.duration_text || '',
  summary: o.summary || '',
  eligibility: String(o.eligibility || '').slice(0, 20000),
  benefits: String(o.benefits || '').slice(0, 20000),
  how_to_apply: String(o.how_to_apply || '').slice(0, 20000),
  documents: String(o.documents || '').slice(0, 5000),
  apply_link: o.apply_link || '',
  image_url: o.image_url || '',
  status: o.status,
  confidence: o.confidence,
  sources: join(o.sources),
  source_url: o.canonical_url || '',
  last_verified_at: o.last_verified_at || '',
  synced_at: new Date().toISOString(),
}}));
