#!/usr/bin/env bash
# Apply db/*.sql in order.
#
# Two modes:
#   SUPABASE_DB_URL set  -> runs them through psql, stopping on the first error.
#   otherwise            -> concatenates them to one file and copies it to the
#                           clipboard, for pasting into Supabase Studio's SQL
#                           Editor. No connection string needed.
#
# Migrations are append-only and each one is idempotent, so re-running is safe.
set -euo pipefail
cd "$(dirname "$0")/.."
[ -f .env ] && set -a && . ./.env && set +a

files=(db/000_pre_migration.sql db/001_schema.sql db/002_views.sql db/003_seed.sql)
for f in db/0[0-9][0-9]_*.sql; do
  [[ " ${files[*]} " == *" $f "* ]] || files+=("$f")   # pick up later migrations
done

if [ -n "${SUPABASE_DB_URL:-}" ]; then
  echo "==> applying ${#files[@]} migrations via psql"
  for f in "${files[@]}"; do
    printf '  %-28s ' "$(basename "$f")"
    if psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -q -f "$f" >/dev/null 2>/tmp/mig.err; then
      echo ok
    else
      echo FAILED; sed 's/^/      /' /tmp/mig.err; exit 1
    fi
  done
  echo "==> verifying"
  psql "$SUPABASE_DB_URL" -q -c \
    "select (select count(*) from sources) as sources,
            (select count(*) from taxonomy_fields) as fields,
            (select count(*) from information_schema.views
              where table_schema='public' and table_name like 'v_%') as views;"
else
  out=/tmp/research-opps-migrations.sql
  { echo "-- Generated by scripts/apply-migrations.sh — paste into Supabase Studio → SQL Editor"
    echo "-- Project: pcctpzvhakdutzzwpmsh"; echo
    for f in "${files[@]}"; do
      echo; echo "-- ═══════════════════════════════════════════════════════════"
      echo "-- $f"; echo "-- ═══════════════════════════════════════════════════════════"; echo
      cat "$f"
    done
  } > "$out"
  lines=$(wc -l < "$out" | tr -d ' ')
  command -v pbcopy >/dev/null && pbcopy < "$out" && copied=" (copied to clipboard)" || copied=""
  echo "==> wrote $out — $lines lines$copied"
  echo
  echo "   Next: open https://supabase.com/dashboard/project/pcctpzvhakdutzzwpmsh/sql/new"
  echo "         paste, Run. Then confirm:  select count(*) from sources;   -- expect 15"
  echo
  echo "   (To use psql instead: put SUPABASE_DB_URL in .env and re-run.)"
fi
